[programs.devnet]
myepicproject = "4R6VJTjscnGSGkhsEtHLi7Bf8Y93HSBea5C1qdtzuUop"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mm-mac/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
